import { z } from 'zod';

export const createIssueSchema = z.object({
    title: z.string().min(1, "Title is required.").max(255),
    description: z.string().min(1, "Description is required."),
    system: z.string().min(1, "System is required.").max(255),
    category: z.string().min(1, "Category is required.").max(255),
    assignedToUserId: z.string().min(1).max(255).optional().nullable(),
    dreadDamage: z.number().min(1).max(10).optional(),
    dreadRepro: z.number().min(1).max(10).optional(),
    dreadExploit: z.number().min(1).max(10).optional(),
    dreadAffected: z.number().min(1).max(10).optional(),
    dreadDiscover: z.number().min(1).max(10).optional(),
    cvssAV: z.string().optional(),
    cvssAC: z.string().optional(),
    cvssPR: z.string().optional(),
    cvssUI: z.string().optional(),
    cvssS: z.string().optional(),
    cvssC: z.string().optional(),
    cvssI: z.string().optional(),
    cvssA: z.string().optional(),
    cvssScore: z.number().optional().nullable(),
    dreadScore: z.number().optional().nullable(),
    deadline: z.coerce.date().optional().nullable(),
});